require_relative 'cryptography/test_message'
require_relative 'linear_algebra/test_vector'
require_relative 'linear_algebra/test_matrix'
require_relative 'telephone/test_telephone'
require_relative 'primes/test_primes'
require_relative 'primes/test_c_primes'
require_relative 'primes/test_primes_implementations'
